//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamionesWebMVCGenMar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GenMarEntities : DbContext
    {
        public GenMarEntities()
            : base("name=GenMarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Camiones> Camiones { get; set; }
        public virtual DbSet<Chofer> Chofer { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vw_Camiones> Vw_Camiones { get; set; }
        public virtual DbSet<Vw_Choferes> Vw_Choferes { get; set; }
        public virtual DbSet<Vw_Rutas> Vw_Rutas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Existe_Licencia(string licencia)
        {
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Existe_Licencia", licenciaParameter);
        }
    
        public virtual ObjectResult<Existe_Matricula_Result> Existe_Matricula(string matricula)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Existe_Matricula_Result>("Existe_Matricula", matriculaParameter);
        }
    
        public virtual ObjectResult<Obtener_Camion_PorId_Result> Obtener_Camion_PorId(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Camion_PorId_Result>("Obtener_Camion_PorId", idCamionParameter);
        }
    
        public virtual ObjectResult<Obtener_Chofer_PorId_Result> Obtener_Chofer_PorId(Nullable<int> idChofer)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Obtener_Chofer_PorId_Result>("Obtener_Chofer_PorId", idChoferParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int Sp_Delete_Camiones(Nullable<int> idCamion)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Camiones", idCamionParameter);
        }
    
        public virtual int Sp_Delete_Chofer(Nullable<int> idChofer)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Chofer", idChoferParameter);
        }
    
        public virtual int Sp_Delete_Ruta(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Ruta", idRutaParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int Sp_Insert_Camion(string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, Nullable<bool> disponibilidad, string uRLFoto, Nullable<System.DateTime> fechaRegistro)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var uRLFotoParameter = uRLFoto != null ?
                new ObjectParameter("URLFoto", uRLFoto) :
                new ObjectParameter("URLFoto", typeof(string));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Insert_Camion", matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, disponibilidadParameter, uRLFotoParameter, fechaRegistroParameter);
        }
    
        public virtual int Sp_Insert_Chofer(string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad, Nullable<System.DateTime> fechaRegistro)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Insert_Chofer", nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter, fechaRegistroParameter);
        }
    
        public virtual int Sp_Insert_Ruta(Nullable<int> idChofer, Nullable<int> idCamion, string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<bool> aTiempo, Nullable<double> distancia, Nullable<System.DateTime> fechaRegistro)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Insert_Ruta", idChoferParameter, idCamionParameter, origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, aTiempoParameter, distanciaParameter, fechaRegistroParameter);
        }
    
        public virtual ObjectResult<Sp_Listar_Camiones_Result> Sp_Listar_Camiones(Nullable<bool> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Listar_Camiones_Result>("Sp_Listar_Camiones", disponibilidadParameter);
        }
    
        public virtual ObjectResult<Sp_Listar_Choferes_Result> Sp_Listar_Choferes(Nullable<bool> disponibilidad)
        {
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Listar_Choferes_Result>("Sp_Listar_Choferes", disponibilidadParameter);
        }
    
        public virtual ObjectResult<Sp_Listar_Rutas_Result> Sp_Listar_Rutas(Nullable<int> aTiempo)
        {
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Listar_Rutas_Result>("Sp_Listar_Rutas", aTiempoParameter);
        }
    
        public virtual ObjectResult<SP_ObtenerRutaPorId_Result> SP_ObtenerRutaPorId(Nullable<int> idRuta)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObtenerRutaPorId_Result>("SP_ObtenerRutaPorId", idRutaParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int Sp_Update_Camion(Nullable<int> idCamion, string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, Nullable<bool> disponibilidad, string uRLFoto)
        {
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var uRLFotoParameter = uRLFoto != null ?
                new ObjectParameter("URLFoto", uRLFoto) :
                new ObjectParameter("URLFoto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Camion", idCamionParameter, matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, disponibilidadParameter, uRLFotoParameter);
        }
    
        public virtual int Sp_Update_Chofer(Nullable<int> idChofer, string nombre, string apPaterno, string apMaterno, string telefono, Nullable<System.DateTime> fechaNacimiento, string licencia, string urlFoto, Nullable<bool> disponibilidad)
        {
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var urlFotoParameter = urlFoto != null ?
                new ObjectParameter("UrlFoto", urlFoto) :
                new ObjectParameter("UrlFoto", typeof(string));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Chofer", idChoferParameter, nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, fechaNacimientoParameter, licenciaParameter, urlFotoParameter, disponibilidadParameter);
        }
    
        public virtual int Sp_Update_Ruta(Nullable<int> idRuta, Nullable<int> idChofer, Nullable<int> idCamion, string origen, string destino, Nullable<System.DateTime> fechaSalida, Nullable<System.DateTime> fechaLlegada, Nullable<bool> aTiempo, Nullable<double> distancia)
        {
            var idRutaParameter = idRuta.HasValue ?
                new ObjectParameter("IdRuta", idRuta) :
                new ObjectParameter("IdRuta", typeof(int));
    
            var idChoferParameter = idChofer.HasValue ?
                new ObjectParameter("IdChofer", idChofer) :
                new ObjectParameter("IdChofer", typeof(int));
    
            var idCamionParameter = idCamion.HasValue ?
                new ObjectParameter("IdCamion", idCamion) :
                new ObjectParameter("IdCamion", typeof(int));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            var destinoParameter = destino != null ?
                new ObjectParameter("Destino", destino) :
                new ObjectParameter("Destino", typeof(string));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("FechaSalida", fechaSalida) :
                new ObjectParameter("FechaSalida", typeof(System.DateTime));
    
            var fechaLlegadaParameter = fechaLlegada.HasValue ?
                new ObjectParameter("FechaLlegada", fechaLlegada) :
                new ObjectParameter("FechaLlegada", typeof(System.DateTime));
    
            var aTiempoParameter = aTiempo.HasValue ?
                new ObjectParameter("ATiempo", aTiempo) :
                new ObjectParameter("ATiempo", typeof(bool));
    
            var distanciaParameter = distancia.HasValue ?
                new ObjectParameter("Distancia", distancia) :
                new ObjectParameter("Distancia", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Ruta", idRutaParameter, idChoferParameter, idCamionParameter, origenParameter, destinoParameter, fechaSalidaParameter, fechaLlegadaParameter, aTiempoParameter, distanciaParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateCamionSP(Nullable<int> camionId, string matricula, string tipoCamion, Nullable<int> modelo, string marca, Nullable<int> capacidad, Nullable<double> kilometraje, Nullable<bool> disponibilidad, string uRLFoto, Nullable<System.DateTime> fechaRegistro)
        {
            var camionIdParameter = camionId.HasValue ?
                new ObjectParameter("CamionId", camionId) :
                new ObjectParameter("CamionId", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var tipoCamionParameter = tipoCamion != null ?
                new ObjectParameter("TipoCamion", tipoCamion) :
                new ObjectParameter("TipoCamion", typeof(string));
    
            var modeloParameter = modelo.HasValue ?
                new ObjectParameter("Modelo", modelo) :
                new ObjectParameter("Modelo", typeof(int));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("Capacidad", capacidad) :
                new ObjectParameter("Capacidad", typeof(int));
    
            var kilometrajeParameter = kilometraje.HasValue ?
                new ObjectParameter("Kilometraje", kilometraje) :
                new ObjectParameter("Kilometraje", typeof(double));
    
            var disponibilidadParameter = disponibilidad.HasValue ?
                new ObjectParameter("Disponibilidad", disponibilidad) :
                new ObjectParameter("Disponibilidad", typeof(bool));
    
            var uRLFotoParameter = uRLFoto != null ?
                new ObjectParameter("URLFoto", uRLFoto) :
                new ObjectParameter("URLFoto", typeof(string));
    
            var fechaRegistroParameter = fechaRegistro.HasValue ?
                new ObjectParameter("FechaRegistro", fechaRegistro) :
                new ObjectParameter("FechaRegistro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCamionSP", camionIdParameter, matriculaParameter, tipoCamionParameter, modeloParameter, marcaParameter, capacidadParameter, kilometrajeParameter, disponibilidadParameter, uRLFotoParameter, fechaRegistroParameter);
        }
    
        public virtual ObjectResult<sp_ExisteEmail_Result> sp_ExisteEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ExisteEmail_Result>("sp_ExisteEmail", emailParameter);
        }
    
        public virtual int sp_InsertarUsuario(string usuario, string password, string email)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarUsuario", usuarioParameter, passwordParameter, emailParameter);
        }
    
        public virtual ObjectResult<sp_Obtenerusuario_Result> sp_Obtenerusuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Obtenerusuario_Result>("sp_Obtenerusuario");
        }
    }
}
