//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamionesWebMVCGenMar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Rutas
    {
        public int IdRuta { get; set; }
        public int IdChofer { get; set; }
        public int IdCamion { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public bool ATiempo { get; set; }
        public double Distancia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
