//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlGastosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosPersonales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosPersonales()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdDatos { get; set; }
        public string Nombre { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> SueldoBase { get; set; }
        public Nullable<int> IdTipoSueldo { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    
        public virtual TipoSueldo TipoSueldo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
