//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlGastosMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ControlGastosEntities : DbContext
    {
        public ControlGastosEntities()
            : base("name=ControlGastosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<DatosPersonales> DatosPersonales { get; set; }
        public virtual DbSet<Gastos> Gastos { get; set; }
        public virtual DbSet<NivelUsuario> NivelUsuario { get; set; }
        public virtual DbSet<TipoSueldo> TipoSueldo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int sp_ActualizarCategoria(Nullable<int> idCategorias, string nombre, string descripcion)
        {
            var idCategoriasParameter = idCategorias.HasValue ?
                new ObjectParameter("IdCategorias", idCategorias) :
                new ObjectParameter("IdCategorias", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarCategoria", idCategoriasParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int sp_ActualizarDatosPersonales(Nullable<int> idDatos, string nombre, string apPaterno, string apMaterno, string telefono, string direccion, Nullable<int> idTipoSueldo, Nullable<decimal> sueldoBase)
        {
            var idDatosParameter = idDatos.HasValue ?
                new ObjectParameter("IdDatos", idDatos) :
                new ObjectParameter("IdDatos", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var idTipoSueldoParameter = idTipoSueldo.HasValue ?
                new ObjectParameter("IdTipoSueldo", idTipoSueldo) :
                new ObjectParameter("IdTipoSueldo", typeof(int));
    
            var sueldoBaseParameter = sueldoBase.HasValue ?
                new ObjectParameter("SueldoBase", sueldoBase) :
                new ObjectParameter("SueldoBase", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarDatosPersonales", idDatosParameter, nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, direccionParameter, idTipoSueldoParameter, sueldoBaseParameter);
        }
    
        public virtual int sp_ActualizarUsario(Nullable<int> idUsuario, Nullable<int> idDatos, string nombre, string email, string password, Nullable<int> idNivelUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idDatosParameter = idDatos.HasValue ?
                new ObjectParameter("IdDatos", idDatos) :
                new ObjectParameter("IdDatos", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var idNivelUsuarioParameter = idNivelUsuario.HasValue ?
                new ObjectParameter("IdNivelUsuario", idNivelUsuario) :
                new ObjectParameter("IdNivelUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarUsario", idUsuarioParameter, idDatosParameter, nombreParameter, emailParameter, passwordParameter, idNivelUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_DropListDatosPersonales_Result> sp_DropListDatosPersonales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DropListDatosPersonales_Result>("sp_DropListDatosPersonales");
        }
    
        public virtual int sp_EliminarCategoria(Nullable<int> idCategorias)
        {
            var idCategoriasParameter = idCategorias.HasValue ?
                new ObjectParameter("IdCategorias", idCategorias) :
                new ObjectParameter("IdCategorias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarCategoria", idCategoriasParameter);
        }
    
        public virtual int sp_EliminarDatosPersonales(Nullable<int> idDatos, Nullable<int> idEstatus)
        {
            var idDatosParameter = idDatos.HasValue ?
                new ObjectParameter("IdDatos", idDatos) :
                new ObjectParameter("IdDatos", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarDatosPersonales", idDatosParameter, idEstatusParameter);
        }
    
        public virtual int sp_EliminarGastos(Nullable<int> idGastos)
        {
            var idGastosParameter = idGastos.HasValue ?
                new ObjectParameter("IdGastos", idGastos) :
                new ObjectParameter("IdGastos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarGastos", idGastosParameter);
        }
    
        public virtual int sp_EliminarUsuario(Nullable<int> idUsuario, Nullable<int> idEstatus)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idEstatusParameter = idEstatus.HasValue ?
                new ObjectParameter("IdEstatus", idEstatus) :
                new ObjectParameter("IdEstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarUsuario", idUsuarioParameter, idEstatusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ExisteEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ExisteEmail", emailParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ExisteUsuario(Nullable<int> idDatos)
        {
            var idDatosParameter = idDatos.HasValue ?
                new ObjectParameter("IdDatos", idDatos) :
                new ObjectParameter("IdDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ExisteUsuario", idDatosParameter);
        }
    
        public virtual ObjectResult<sp_GastosPorUsuario_Result> sp_GastosPorUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GastosPorUsuario_Result>("sp_GastosPorUsuario", idUsuarioParameter);
        }
    
        public virtual int sp_InsertarCategoria(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarCategoria", nombreParameter, descripcionParameter);
        }
    
        public virtual int sp_InsertarDatosPersonales(string nombre, string apPaterno, string apMaterno, string telefono, string direccion, Nullable<int> idTipoSueldo, Nullable<decimal> sueldoBase)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPaternoParameter = apPaterno != null ?
                new ObjectParameter("ApPaterno", apPaterno) :
                new ObjectParameter("ApPaterno", typeof(string));
    
            var apMaternoParameter = apMaterno != null ?
                new ObjectParameter("ApMaterno", apMaterno) :
                new ObjectParameter("ApMaterno", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var idTipoSueldoParameter = idTipoSueldo.HasValue ?
                new ObjectParameter("IdTipoSueldo", idTipoSueldo) :
                new ObjectParameter("IdTipoSueldo", typeof(int));
    
            var sueldoBaseParameter = sueldoBase.HasValue ?
                new ObjectParameter("SueldoBase", sueldoBase) :
                new ObjectParameter("SueldoBase", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarDatosPersonales", nombreParameter, apPaternoParameter, apMaternoParameter, telefonoParameter, direccionParameter, idTipoSueldoParameter, sueldoBaseParameter);
        }
    
        public virtual int sp_InsertarGastos(Nullable<int> idUsuario, Nullable<int> idCategorias, Nullable<decimal> monto, string descripcion)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idCategoriasParameter = idCategorias.HasValue ?
                new ObjectParameter("IdCategorias", idCategorias) :
                new ObjectParameter("IdCategorias", typeof(int));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("Monto", monto) :
                new ObjectParameter("Monto", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarGastos", idUsuarioParameter, idCategoriasParameter, montoParameter, descripcionParameter);
        }
    
        public virtual int sp_InsertarUsuario(Nullable<int> idDatos, Nullable<int> idNivelUsuario, string nombre, string email, string password)
        {
            var idDatosParameter = idDatos.HasValue ?
                new ObjectParameter("IdDatos", idDatos) :
                new ObjectParameter("IdDatos", typeof(int));
    
            var idNivelUsuarioParameter = idNivelUsuario.HasValue ?
                new ObjectParameter("IdNivelUsuario", idNivelUsuario) :
                new ObjectParameter("IdNivelUsuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarUsuario", idDatosParameter, idNivelUsuarioParameter, nombreParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_ListarCategoria_Result> sp_ListarCategoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarCategoria_Result>("sp_ListarCategoria");
        }
    
        public virtual ObjectResult<sp_ListarDatosPersonales_Result> sp_ListarDatosPersonales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarDatosPersonales_Result>("sp_ListarDatosPersonales");
        }
    
        public virtual ObjectResult<sp_ListarGastos_Result> sp_ListarGastos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarGastos_Result>("sp_ListarGastos");
        }
    
        public virtual ObjectResult<sp_ListarUsuarios_Result> sp_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarUsuarios_Result>("sp_ListarUsuarios");
        }
    
        public virtual ObjectResult<sp_LoginUsuario_Result> sp_LoginUsuario(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LoginUsuario_Result>("sp_LoginUsuario", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerCategoriasPorId_Result> sp_ObtenerCategoriasPorId(Nullable<int> idCategorias)
        {
            var idCategoriasParameter = idCategorias.HasValue ?
                new ObjectParameter("IdCategorias", idCategorias) :
                new ObjectParameter("IdCategorias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerCategoriasPorId_Result>("sp_ObtenerCategoriasPorId", idCategoriasParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerDatosPersonalesID_Result> sp_ObtenerDatosPersonalesID(Nullable<int> idDatos)
        {
            var idDatosParameter = idDatos.HasValue ?
                new ObjectParameter("IdDatos", idDatos) :
                new ObjectParameter("IdDatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerDatosPersonalesID_Result>("sp_ObtenerDatosPersonalesID", idDatosParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerUsuarioId_Result> sp_ObtenerUsuarioId(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerUsuarioId_Result>("sp_ObtenerUsuarioId", idUsuarioParameter);
        }
    }
}
