//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlGastosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastos
    {
        public int IdGastos { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdCategorias { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdEstatus { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
